services:
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
          - "@oc_platform.beta.html_adder"
          - "2017-12-25"
        tags:
          - { name: kernel.event_listener, event: kernel.response, method: processBeta}

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.email.application_creation:
            class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
            arguments:
                - "@oc_platform.email.application_mailer"
            tags:
                - { name: doctrine.event_listener, event: postPersist }


    oc_platform.email.purger.advert:
            class: OC\PlatformBundle\Purger\AdvertPurger
            arguments:
                - "@doctrine.orm.entity_manager"

    oc_platform.validator.antiflood:
            class: OC\PlatformBundle\Validator\AntiFloodValidator
            arguments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
            tags:
                - { name: validator.constraint_validator, alias: oc_platform_antiflood }

#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
